apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: etcd
  publishNotReadyAddresses: true
  ports:
    - name: etcd-client
      port: 2379
    - name: etcd-server
      port: 2380
