apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
spec:
  replicas: 1
  serviceName: etcd
  selector:
    matchLabels:
      app.kubernetes.io/name: etcd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: etcd
    spec:
      initContainers:
        - name: nslookup
          image: alpine:3.20
          command: ["/bin/sh", "-c"]
          args: ["until nslookup $(ETCD_NAME).etcd.etcd.svc.cluster.local; do sleep 1; done"]
          env:
            - name: ETCD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.15
          ports:
            - name: etcd-client
              containerPort: 2379
            - name: etcd-server
              containerPort: 2380
          volumeMounts:
            - name: etcd-data
              mountPath: /data
          env:
            - name: ETCD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ETCD_DISCOVERY_SRV
              value: etcd
            - name: ETCD_INITIAL_CLUSTER_TOKEN
              value: etcd-cluster
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: http://$(ETCD_NAME).etcd:2379
            - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
              value: http://$(ETCD_NAME).etcd:2380
            - name: ETCD_LISTEN_CLIENT_URLS
              value: http://0.0.0.0:2379
            - name: ETCD_LISTEN_PEER_URLS
              value: http://0.0.0.0:2380
            - name: ETCD_DATA_DIR
              value: /data
            - name: ETCDCTL_DISCOVERY_SRV
              value: etcd
  volumeClaimTemplates:
    - metadata:
        name: etcd-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 32Mi
