- job_name: 'additionalScrapeConfigs/jaeger/opentelemetry-collector/exporters/prometheus'

  kubernetes_sd_configs:
    - role: pod

  relabel_configs:

    - source_labels: [ __meta_kubernetes_namespace ]
      action: keep
      regex: jaeger

    - source_labels: [ __meta_kubernetes_pod_label_app_kubernetes_io_name ]
      action: keep
      regex: opentelemetry-collector

    - source_labels: [ __address__ ]
      action: replace
      regex: (.*)
      replacement: ${1}:9113
      target_label: __address__

    - source_labels: [ __meta_kubernetes_namespace ]
      action: replace
      target_label: kubernetes_namespace

    - source_labels: [ __meta_kubernetes_pod_name ]
      action: replace
      target_label: kubernetes_pod_name
