apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guestbook
spec:
  description: Guestbook Project
  sourceRepos:
    - https://github.com/argoproj/argocd-example-apps.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: guestbook
