apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  allInOne:
    metricsStorage:
      type: prometheus
    options:
      prometheus:
        server-url: http://prometheus-operated.prometheus.svc:9090
