apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector-exporters
  labels:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/component: exporters
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: opentelemetry-collector
  ports:
    - name: prometheus
      port: 9113
      targetPort: 9113
