apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coredns
resources:
  - namespace.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: coredns
    files:
      - assets/Corefile
