resources:
  - https://github.com/grafana-operator/grafana-operator//deploy/manifests?ref=v4.6.0

patchesJson6902:
  - path: patch-deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: grafana-operator-controller-manager
