apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
spec:
  client:
    preferService: true
  config:
    auth.anonymous:
      enabled: true
  dashboardLabelSelector:
    - matchExpressions:
        - key: grafana.com/namespace
          operator: In
          values:
            - grafana
        - key: grafana.com/name
          operator: In
          values:
            - grafana
    # matchLabels doesn't work
    # - matchLabels:
    #     grafana.com/namespace: grafana
    #     grafana.com/name: grafana
