apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:1.26-alpine
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: confd
              mountPath: /etc/nginx/conf.d
            - name: templates
              mountPath: /etc/nginx/templates
          securityContext:
            allowPrivilegeEscalation: false
            # readOnlyRootFilesystem: true
      volumes:
        - name: confd
          emptyDir: {}
        - name: templates
          configMap:
            name: nginx-templates
            defaultMode: 0444
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
