apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx
resources:
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - service.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: nginx-templates
    files:
      - assets/default.conf.template
