apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: opentelemetrycollectors.opentelemetry.io
  annotations:
    cert-manager.io/inject-ca-from: opentelemetry-operator/opentelemetry-operator-serving-cert
