apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry
spec:
  config: |

    receivers:
      otlp:
        protocols:
          http:

    exporters:
      logging:
        loglevel: debug

    service:
      pipelines:
        traces:
          receivers: [ otlp ]
          exporters: [ logging ]
