apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.60.0
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
  config: |

    receivers:
      otlp:
        protocols:
          http:

    processors:
      spanmetrics:
        metrics_exporter: prometheus

    exporters:
      logging:
      jaeger:
        endpoint: jaeger-collector:14250
        tls:
          insecure: true
      prometheus:
        endpoint: 0.0.0.0:9113

    service:
      pipelines:
        traces:
          receivers: [ otlp ]
          processors: [ spanmetrics ]
          exporters: [ logging, jaeger ]
        metrics:
          receivers: [ otlp ]
          exporters: [ prometheus ]
