apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../coredns
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: coredns-config
    behavior: replace
    files:
      - assets/Corefile
